robot_name: 'spot'

joint_names: &jn ["LF_HAA", "LF_HFE", "LF_KFE", "LH_HAA", "LH_HFE", "LH_KFE", "RF_HAA", "RF_HFE", "RF_KFE", "RH_HAA", "RH_HFE", "RH_KFE"]
base_name: "base"

state_topic: "spot/state"
command_topic: "spot/command"
change_controller_topic: "spot/change_controller"
contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"]

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.75, -1.6, 0.0, 0.75, -1.6, 0.0, 0.75, -1.6, 0.0, 0.75, -1.6]  # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.6, -2.5, 0.0, 1.6, -2.5, 0.0, 1.6, -2.5, 0.0, 1.6, -2.5]  # LF, RF, LH, RH
  kp: 300
  kd: 10
  interpolation_time: 1.0
  rate: 50

mpc_controller:
  wbc_type: "sqp"
  reference_trajectory:
    terrain_topic: "/convex_plane_decomposition_ros/filtered_map"
    reference_topic: "/anymal_mpc_target"
    observation_topic: "/anymal_mpc_observation"
    traj_dt: 0.1
    traj_knots: 10
    blind: true

reference_generator:
  type: "twist"
  twist:
    topic: "cmd_vel"

estimator_type: "ground_truth"
